#! /bin/bash

if [ -z "$1" ]
then
  echo "File not specified"
  exit 1
elif [ ! -e "$1" ]
then
  echo "File $1 does not found"
  exit 1
fi

CUR_BUILD=`grep "^BUILD=" "$1"`

if [ $? -ne 0 ]
then
  echo "BUILD value not found"
  exit 1
fi

NEW_BUILD_VAL=1

echo "setting BUILD to $NEW_BUILD_VAL"

sed -i "s@^$CUR_BUILD@BUILD=$NEW_BUILD_VAL@" "$1"
