'\" t
.\"     Title: cqsearch
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 04/10/2017
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "CQSEARCH" "1" "04/10/2017" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cqsearch \- create codequery database
.SH "SYNOPSIS"
.sp
\fBcqsearch\fR [\fI\-s <sqdbfile>\fR [\fI\-p <n>\fR] [\fI\-t <term>\fR] \-[\fIe|f\fR] ] [\fI\-d\fR] [\fI\-v\fR] [\fI\-h\fR]
.SH "OPTIONS"
.PP
\fB\-s\fR
.RS 4
CodeQuery sqlite3 db file path
.RE
.PP
\fB\-p <n>\fR
.RS 4
parameter is a number denoted by n
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
1: Symbol (default)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
2: Function or macro definition
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
3: Class or struct
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
4: Files including this file
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
5: Full file path
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
6: Functions calling this function
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
7: Functions called by this function
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
8: Calls of this function or macro
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
9: Members and methods of this class
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
10: Class which owns this member or method
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
11: Children of this class (inheritance)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
12: Parent of this class (inheritance)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
13: Functions or macros inside this file
.RE
.RE
.PP
\fB\-t\fR
.RS 4
search term without spaces if Exact Match is switched off, wild card searches are possible\&. Use
*
and
?
.RE
.PP
\fB\-e\fR
.RS 4
Exact Match switched ON Case\-sensitive
.RE
.PP
\fB\-f\fR
.RS 4
Exact Match switched OFF (fuzzy search) Case\-insensitive with wild card search (default)
.RE
.PP
\fB\-d\fR
.RS 4
debug
.RE
.PP
\fB\-v\fR
.RS 4
version
.RE
.PP
\fB\-h\fR
.RS 4
help
.RE
.sp
The combinations possible are \fB\-s\fR \fB\-t\fR \fB\-e\fR, \fB\-s\fR \fB\-t\fR \fB\-f\fR\&. The additional optional arguments are \fB\-d\fR\&.
.SH "COPYRIGHT"
.sp
Copyright 2013\-2015 ruben2020 \fIhttps://github\&.com/ruben2020/\fR
.sp
Website: \fIhttps://github\&.com/ruben2020/codequery\fR
.SH "AUTHOR"
.sp
This manual page was written by ChangZhuo Chen \fI<\fR\fIczchen@debian\&.org\fR\fI>\fR for the \fBDebian GNU/Linux system\fR (but may be used by others)\&.
