#! /bin/bash

if [ -z "$1" ]
then
  echo "module not specified"
  exit 1
fi
  
mods=~/tmp/cpan/MINICPAN/modules/02packages.details.txt.gz

MOD=`zgrep "^$1\\s" $mods`

if [ $? -ne 0 ]
then
  echo "module $1 not found"
  exit 1
fi

echo $MOD

