#! /bin/bash

if [ -z "$2" ]
then
  echo "New version not specified"
  exit 1
elif [ ! -e "$1" ]
then
  echo "File $1 does not found"
  exit 1
fi

CUR_VER=`grep "^VERSION=" "$1"`

if [ $? -ne 0 ]
then
  echo "VERSION value not found"
  exit 1
fi

echo "setting VERSION to $2"

sed -i "s@^$CUR_VER@VERSION=$2@" "$1"
