#!/usr/bin/expect -f

set timeout 10000
match_max 100000

stty -echo
send_user "Password: "
expect_user -re "(.*)\n"
set password $expect_out(1,string)
stty echo

set arg1 [lindex $argv 0];
set arg2 [lindex $argv 1];

spawn sh -c "./zbuildscript $arg1 $arg2"

expect {
    Password: { send "$password\n" ; exp_continue }
    timeout { exit }
    alldone
}
