#!/usr/bin/expect -f

set timeout 10000
match_max 100000

stty -echo
send_user "Password: "
expect_user -re "(.*)\n"
set password $expect_out(1,string)
stty echo

spawn sh -c "./zbuildlist"

expect {
    Password: { send "$password\n" ; exp_continue }
    timeout { exit }
    alldone
}
